### ISSUE TITLE
console message in new install Warning: A component is changing an uncontrolled input

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-hyva-checkout#110]
In a new install of the develop branch I am greeted with the following console warning.
```
index.js:1 Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at Field (http://localhost:3000/static/js/bundle.js:24294:23)
    at div
    at TextInput (http://localhost:3000/static/js/bundle.js:86954:17)
    at div
    at ShippingAddressForm (http://localhost:3000/static/js/bundle.js:91330:118)
    at div
    at div
    at ToggleBox (http://localhost:3000/static/js/bundle.js:87474:23)
    at div
    at Card (http://localhost:3000/static/js/bundle.js:86458:23)
    at form
    at http://localhost:3000/static/js/bundle.js:24383:22
    at ShippingAddressFormikProvider (http://localhost:3000/static/js/bundle.js:91678:23)
    at http://localhost:3000/static/js/bundle.js:91042:25
    at ShippingAddress (http://localhost:3000/static/js/bundle.js:90972:90)
    at http://localhost:3000/static/js/bundle.js:83289:23
    at AddressWrapper (http://localhost:3000/static/js/bundle.js:83203:23)
    at div
    at div
    at div
    at div
    at div
    at CheckoutFormWrapper (http://localhost:3000/static/js/bundle.js:82653:23)
    at CheckoutForm (http://localhost:3000/static/js/bundle.js:82407:94)
    at StepProvider (http://localhost:3000/static/js/bundle.js:96144:23)
    at Formik (http://localhost:3000/static/js/bundle.js:24051:19)
    at CheckoutFormProvider (http://localhost:3000/static/js/bundle.js:95935:23)
    at CartDataProvider (http://localhost:3000/static/js/bundle.js:94588:23)
    at AppDataProvider (http://localhost:3000/static/js/bundle.js:93736:23)
    at Checkout
```

I suspect this is due to one of the `TextInput` components inside `ShippingAddressForm`

**Comment by progammer-rkt** [comment]
This is a long persisting issue in the checkout and really didn't get time to resolve it. This is no longer be there with this #137

**Comment by progammer-rkt** [comment]
Fix reached `develop` branch and hence, closing this issue.
